#!/bin/sh

VERSION=$(uname -r)

echo '/etc/modprobe.d
/etc/event.disabled
/etc/event.disabled/hvc0.conf
/etc/init/tty1.conf
/etc/init/ttyS0.conf
/lib/modules'

echo "/lib/modules/$VERSION"
echo "/lib/modules/$VERSION/modules.alias"
echo "/lib/modules/$VERSION/modules.alias.bin"
echo "/lib/modules/$VERSION/modules.builtin"
echo "/lib/modules/$VERSION/modules.builtin.alias.bin"
echo "/lib/modules/$VERSION/modules.builtin.bin"
echo "/lib/modules/$VERSION/modules.dep"
echo "/lib/modules/$VERSION/modules.dep.bin"
echo "/lib/modules/$VERSION/modules.devname"
echo "/lib/modules/$VERSION/modules.order"
echo "/lib/modules/$VERSION/modules.softdep"
echo "/lib/modules/$VERSION/modules.symbols"
echo "/lib/modules/$VERSION/modules.symbols.bin"
