#!/bin/sh
# vim: nospell

if [ "$1" != install ] && [ "$1" != configure ]
then
	exit 0
fi

config_hostname()
{
	# Get the current hostname
	HOSTNAME=$(cat /etc/hostname)

	# Get the new hostname
	db_get task-teacats/hostname

	# Skip if the hostname is unchanged
	test "${HOSTNAME}" = "${RET}" && return 0

	# Set the hostname
	HOSTNAME=${RET}
	export HOSTNAME

	# Set the hostname file
	echo "${HOSTNAME}" >/etc/hostname

	# Set the hostname itself
	hostname -F /etc/hostname

	TMP=$(mktemp)

	# Remove leading host lines from /etc/hosts
	sed -e '/^127.0.[01].1/d' -e '/^127.0.[01].1/{//,$p}' /etc/hosts >"$TMP"

	# Write the new hosts file
	{
		echo "127.0.0.1  $HOSTNAME";
		echo "127.0.1.1  ${HOSTNAME%%.*} localhost";
		cat "$TMP"
	} >/etc/hosts

	rm -f "$TMP"

	# See if we succeeded
	test "${HOSTNAME}" = "$(hostname)"
	return $?
}

config_network()
{
	# Have a file to write the new configuration to
	TMP=$(mktemp)
	exec 9>"$TMP"

	# Get the name of the interface we want
	db_get task-teacats/interface
	INTERFACE=$RET

	# Write the header
	echo "# Auto-configured Network interface" >&9
	echo "# vim: nospell" >&9
	echo "[Match]" >&9
	echo "Name=$INTERFACE" >&9
	echo >&9
	echo "[Network]" >&9
	echo "Description=$INTERFACE Interface" >&9
	echo "Domains=tea-cats.co.uk" >&9
	echo "DHCP=ipv6" >&9

	# Write the IPv6 section, if set
	db_get task-teacats/address-ipv6

	if [ -n "$RET" ]
	then
		ADDR=$RET
		db_get task-teacats/netmask-ipv6

		echo >&9
		echo "[Address]" >&9
		echo "Address=$ADDR/${RET:-128}" >&9
	fi

	db_get task-teacats/gateway-ipv6
	if [ -n "$RET" ]
	then
		echo >&9
		echo "[Route]" >&9
		echo "Gateway=$RET" >&9
		echo "Scope=global" >&9
		echo "Destination=::0/0" >&9
	fi

	# Write the IPv4 section, if set
	db_get task-teacats/address-ipv4

	if [ -n "$RET" ]
	then
		ADDR=$RET
		db_get task-teacats/netmask-ipv4

		echo >&9
		echo "[Address]" >&9
		echo "Address=$ADDR/${RET:-32}" >&9
	fi

	db_get task-teacats/gateway-ipv4
	if [ -n "$RET" ]
	then
		echo >&9
		echo "[Route]" >&9
		echo "Gateway=$RET" >&9
		echo "Scope=global" >&9
		echo "Destination=0.0.0.0/0" >&9
	fi

	db_get task-teacats/address-local
	if [ -n "$RET" ]
	then
		ADDR=$RET
		db_get task-teacats/netmask-local

		echo >&9
		echo "[Address]" >&9
		echo "Address=$ADDR/${RET:-32}" >&9
	fi

	exec 9>&-

	TARGET=/etc/systemd/network/${INTERFACE}.network

	if test ! -e "$TARGET" || ! diff -q "$TARGET" "$TMP" >/dev/null
	then
		echo "Installing new interface file"
		test -e "$TARGET" && mv "$TARGET" "/etc/network/$INTERFACE.$(date +%s).bak"
		mv "$TMP" "$TARGET"
		chmod 644 "$TARGET"
	fi

	rm -f "$TMP"

	return 0
}

update_config()
{
	TMP=$(mktemp)
	TARGET=$2

	HOSTNAME=$(hostname)
	db_get task-teacats/interface
	INTERFACE="$RET"
	db_get task-teacats/address-ipv4
	PUBLIC_IPV4="$RET"
	db_get task-teacats/address-ipv6
	PUBLIC_IPV6="$RET"
	db_get task-teacats/address-local
	LOCAL_IPV4="$RET"

	sed "$1" >"$TMP" \
	  -e "s/~~hostname~~/$HOSTNAME/" \
	  -e "s/~~interface~~/$INTERFACE/" \
	  -e "s/~~ipv4_public~~/$PUBLIC_IPV4/" \
	  -e "s/~~ipv6_public~~/$PUBLIC_IPV6/" \
	  -e "s/~~ipv4_local~~/$LOCAL_IPV4/"

	if test ! -e "$TARGET" || ! diff -q "$TARGET" "$TMP" >/dev/null
	then
		mv "$TARGET" "$TARGET.$(date +%s).bak"
		mv "$TMP" "$TARGET"
		RET=0
	else
		RET=1
	fi

	rm -f "$TMP"

	return $RET
}

config_postfix()
{
	if update_config /usr/share/etc/main.cf /etc/postfix/main.cf
	then
		echo "Installing new postfix config"
		chmod 644 \
			/etc/postfix/main.cf \
			/etc/systemd/system/postfix.service.d/override.conf

		systemctl condrestart postfix.service || return 1
	fi

	return 0
}

config_ssh()
{
	if [ ! -s /etc/ssh/ssh_host_ed25519_key ]
	then
		echo "Generating ssh ed25519 key"
		ssh-keygen -t ed25519 -b 512  -f /etc/ssh/ssh_host_ed25519_key -N '' -C "$HOSTNAME"
	fi

	if [ -s /etc/ssh/ssh_host_rsa_key ]
	then
		echo >/etc/ssh/ssh_host_ecdsa_key
		echo >/etc/ssh/ssh_host_ecdsa_key.pub
	fi

	if [ -s /etc/ssh/ssh_host_ecdsa_key ]
	then
		echo >/etc/ssh/ssh_host_ecdsa_key
		echo >/etc/ssh/ssh_host_ecdsa_key.pub
	fi

	if [ -s /etc/ssh/ssh_host_dsa_key ]
	then
		echo >/etc/ssh/ssh_host_dsa_key
		echo >/etc/ssh/ssh_host_dsa_key.pub
	fi

	if update_config /usr/share/etc/sshd_config /etc/ssh/sshd_config
	then
		echo "Installing new ssh config"
		systemctl condrestart ssh.service || return 1
	fi

	return 0
}

config_ntp()
{
	if update_config /usr/share/etc/ntp.conf /etc/ntp.conf
	then
		echo "Installing new ntp config"
		chmod 644 /etc/ntp.conf
		systemctl condrestart ntp.service || return 1
	fi

	return 0
}

# Sets global umask of 027
config_umask()
{
	if ! grep '^umask' /etc/profile >/dev/null
	then
		echo "Adding umask 027 to /etc/profile"
		echo 'umask 027' >> /etc/profile
	fi

	if ! grep '^umask' /etc/zsh/zshenv >/dev/null
	then
		echo "Adding umask 027 to /etc/zsh/zshenv"
		echo 'umask 027' >> /etc/zsh/zshenv
	fi
}

# Set up 30 timeout on root sessions
config_timeout()
{
	if ! grep '^	export TMOUT=30' /etc/profile
	then
		echo "Adding root timeout to /etc/profile"
		echo 'test "$(id -u)" -eq 0 &&
{
	export TMOUT=30
	export TIMEOUT=30
	readonly TMOUT
	readonly TIMEOUT
}' >>/etc/profile
	fi

	if ! grep '^    export TMOUT=30' /etc/zsh/zshrc >/dev/null
	then
		echo "Adding root timeout to /etc/zsh/zshrc"
		echo '
test "$(id -u)" -eq 0 &&
{
	export TMOUT=30
	export TIMEOUT=30
	readonly TMOUT
	readonly TIMEOUT
}' >>/etc/zsh/zshrc
	fi

}

# Restricts the use of `su` to the superuser
config_su()
{
	STAT=$(dpkg-statoverride --list /bin/su)

	if [ $? -eq 1 ]
	then
		echo "Restricting /bin/su to root"
		dpkg-statoverride --update --add root root 0700 /bin/su
	fi

	if [ "$STAT" != "root root 700 /bin/su" ]
	then
		echo "(Re)Restricting /bin/su to root"
		dpkg-statoverride --remove /bin/su
		dpkg-statoverride --update --add root root 0700 /bin/su
	fi
}

config_passwords()
{
	echo "Removing shells from system accounts"

	exec 3</etc/passwd

	while read -r USERLINE
	do
		USER=${USERLINE%%:*}
		USER_SHELL=${USERLINE##*:}

		PASS_LINE=$(getent shadow "$USER")

		PASS=${PASS_LINE#"$USER:"}
		PASS=${PASS%%:*}

		if [ "$USER" = "root" ]
		then
			if [ -n "$PASS" ]
			then
				echo 'root:*' | chpasswd -e
			fi

			continue
		fi

		if [ '*' = "$PASS" ] || [ '\!' = "$PASS" ]
		then
			if [ "$USER_SHELL" != "/bin/false" ]
			then
				chsh "$USER" --shell "/bin/false"
			fi
		fi

		if [ '\!' = "$PASS" ]
		then
			echo "$USER:*" | chpasswd -e
		fi
	done <&3

	exec 3<&-
}

. /usr/share/debconf/confmodule

# Variables for which sections are active
DO_HOSTNAME=0
DO_NETWORK=0
DO_MAIL=0
DO_SSH=0
DO_NTP=0

# Get the selected sections as a string
db_get task-teacats/config

# Set up variables
SECTIONS=$RET
SECTION=

# Loop over the selected list
while [ "$SECTION" != "$SECTIONS" ]
do
	SECTION=${SECTIONS%%, *}
	SECTIONS=${SECTIONS#*, }

	case ${SECTION} in
		Hostname) DO_HOSTNAME=1;;
		Network)  DO_NETWORK=1;;
		Postfix)  DO_MAIL=1;;
		SSH)      DO_SSH=1;;
		NTP)      DO_NTP=1;;
	esac
done

test ${DO_HOSTNAME} -eq 1 && config_hostname
test ${DO_NETWORK}  -eq 1 && config_network
test ${DO_MAIL}     -eq 1 && config_postfix
test ${DO_SSH}      -eq 1 && config_ssh
test ${DO_NTP}      -eq 1 && config_ntp

config_umask
config_su
config_passwords

postmap /etc/postfix/tls_policy
